[package]
name = "ray-tracer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
libc = { version = "0.2.161", optional = true }
rand = "0.8.5"

[features]
default = []
execution = ["libc"]
